---
- name: Test installation of kubelogin
  hosts: all
  tasks:
    - name: Install kubelogin
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'kubelogin --version'
      command: /usr/local/bin/kubelogin --version
      changed_when: false
      register: kubelogin_test_output
    - name: Output from 'kubelogin --version'
      debug:
        msg: '{{ kubelogin_test_output.stdout }}'
