---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/kubelogin --version
    register: kubelogin_test_output
  - name: kubelogin --version
    debug:
      msg: '{{ kubelogin_test_output.stdout }}'
